name: Go package
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Enforce formatting with gofmt
      run: |
        gofmt -l .
        test -z "$(gofmt -l . | tr -d '\n')"

   build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -covermode=atomic -coverprofile=coverage.out ./...

    - name: Update releases
      run: |
        go get fyne.io/fyne/v2/cmd/fyne
        fyne package -os linux
        fyne package -os windows
    - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            ./archon.tar.gz
            ./archon.exe